### ISSUE TITLE
Dead status overlay

### ISSUE THREAD

**Issue by amcvfx** [ironmonk88/always-hp#5]
Hi thanks for the useful module!
I'm having a problem with an unwanted overlay icon being added to tokens when they are set to dead then given full HP again. I use a custom triggered death overlay on tokens when they reach zero, which works, but then when the token is given full HP another overlay icon appears which I don't need.

My custom overlay:
![image](https://user-images.githubusercontent.com/35099081/104713434-2a985e80-5724-11eb-8d69-86f83d2004a1.png)

The other overlay that turns on when those same tokens are given full HP:
![image](https://user-images.githubusercontent.com/35099081/104713549-54ea1c00-5724-11eb-996c-0a278adca493.png)

I'm assuming this module uses its own dead status overlay? Could we have an option to turn that off?

**Comment by ironmonk88** [comment]
It's just the standard overlay, but I have a feeling that yours is going on and off, while the standard is only going on and not turning off when your custom one is turned off.  So it shows up once the token is healed and your custom is removed.
I'm assuming you're using Pathfinder?

Working on adding the setting.

**Comment by amcvfx** [comment]
I’m on d&d 5th. The standard overlay for death doesn’t trigger when HP is reduced to 0 with HP values and raised again with values. It just seems to be when the death and full health buttons are used?

**Comment by ironmonk88** [comment]
I think I get what's happening.  Reconsidered how the dead status was being added.  Originally the skull would toggle it, but realized that makes less sense in practice than it did in my head.  So the skull will turn it on and the heart will turn it off now.  If you don't want to adjust the dead status you can right-click either button and it will just change the HP and not affect the dead status.

**Comment by Falerion-git** [comment]
I think there should be another option to toggle the dead status icon. Consider the following situation:
A token receives enough damage to go to zero. The GM just hit the skull button and the tokens HP is set to 0 and the dead status is assigned. Now, often it happens in real gameplay that this happened on error (I think this is not that unusual in manual gameplay) and the token is actually still alive.
To adjust for that you would give the token some HP back, but then you have to go to manual remove the dead status from it (or from many if you selected many tokens). You also don't want to hit the heart button, because it will bring them back to full live.
How about adding a SHIFT+left click on the skull button to still toggle the dead status on the token?

**Comment by ironmonk88** [comment]
Technically you could achieve this by right-clicking the skull.  It won't apply the status that way.  And I added functionality to remove the status if the character is healed by even one point.  But there's always the possibility of forgetting to right-click.  So I've added the shift-click to toggle the status.

**Comment by ironmonk88** [comment]
Closing the issue as I think the original issue was resolved
